# Generated by Django 5.0 on 2024-08-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SongInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_id", models.CharField(db_index=True, max_length=300, null=True)),
                ("title", models.CharField(max_length=200, null=True)),
                ("danceability", models.FloatField(default=0.0, null=True)),
                ("energy", models.FloatField(default=0.0, null=True)),
                ("mode", models.IntegerField(default=0, null=True)),
                ("acousticness", models.FloatField(default=0.0, null=True)),
                ("tempo", models.FloatField(default=0.0, null=True)),
                ("duration_ms", models.FloatField(default=0.0, null=True)),
                ("num_sections", models.IntegerField(default=0, null=True)),
                ("num_segments", models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
