# Generated by Django 5.0 on 2024-08-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_songinfo_star_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songinfo",
            name="star_rating",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, null=True
            ),
        ),
    ]
